[package]
name = "backlight-follower"
version = "0.1.0"
authors = ["Marek Černoch <marek.cernoch@email.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inotify = "0.8"
rust-ini = "0.14"

